      INTEGER FUNCTION LSTRIM(BUFF)
C
C     ELIMINATE FINAL BLANKS AND FINAL NOT PRINTABLE CHARACTERS
C
C     - BUFF (CH): STRING (INPUT)
C
C     LSTRIM = LENGHT WITHOUT FINAL BLANKS
C
      IMPLICIT NONE
C
      CHARACTER BUFF*(*)
      INTEGER K
C
      DO 1000 K=LEN(BUFF),1,-1
         IF( BUFF(K:K).GT.' '.AND.  BUFF(K:K).LE.'~' ) THEN
             LSTRIM=K
             RETURN
         ENDIF
1000  CONTINUE
      LSTRIM=0
      RETURN
      END
