      FUNCTION LSTRIML(BUFF)
C
C     ELIMINATE LEADING BLANKS AND NOT PRINTABLE CHARACTERS
C
C     - BUFF (CH): STRING (INPUT)
C
C     LSTRIML = LENGHT WITHOUT LEADING AND TRAILING BLANKS
C
C
C     RBI Dec 15, 2008

      CHARACTER BUFF*(*)
C
      DO K=1,LEN(BUFF)
         IF( BUFF(K:K).GT.' '.AND.  BUFF(K:K).LE.'~' ) THEN
             LSTRIML = K
             RETURN
         ENDIF
      ENDDO
      LSTRIML = 0
      RETURN
      END
